# Generated by Django 3.0.6 on 2021-03-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_id',
            new_name='product_name',
        ),
    ]
