# Generated by Django 3.0.6 on 2021-03-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210306_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
